services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hedhog
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: hedhog
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hedhog
      MYSQL_USER: hedhog
      MYSQL_PASSWORD: changeme
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost -u root -proot']
      interval: 10s
      timeout: 5s
      retries: 5
