export enum EnumFieldType {
  RICHTEXT = 'richtext',
  TEXTAREA = 'textarea',
  COLOR = 'color',
  TEXT = 'text',
  FILE = 'file',
  PASSWORD = 'password',
  RADIO = 'radio',
  CHECKBOX = 'checkbox',
  RANGE = 'range',
  SELECT = 'select',
  COMBOBOX = 'combobox',
  MULTISELECT = 'multiselect',
  DATEPICKER = 'datepicker',
  SHEETPICKER = 'sheetpicker',
  SWITCH = 'switch',
  SWITCH_LIST = 'switchlist',
  NUMBER = 'number',
  PICKER = 'picker',
  HTML = 'html',
}
