import { File } from './File';
import { PersonType } from './PersonType';
import { PersonCustom } from './PersonCustom';
import { PersonDocument } from './PersonDocument';
import { ChatMessage } from './ChatMessage';
import { SubscriptionPerson } from './SubscriptionPerson';
import { PersonContact } from './PersonContact';
import { ChatPerson } from './ChatPerson';
import { PersonUser } from './PersonUser';
import { PersonAddress } from './PersonAddress';
import { Payment } from './Payment';
import { PersonValue } from './PersonValue';
import { SubscriptionCancel } from './SubscriptionCancel';
import { Rating } from './Rating';
import { WalletPerson } from './WalletPerson';

export type Person = {
  id?: number;
  name: string;
  photo_id?: number;
  type_id: number;
  birth_at?: string;
  created_at?: string;
  updated_at?: string;
  file?: File;
  person_type?: PersonType;
  person_custom?: PersonCustom[];
  person_document?: PersonDocument[];
  chat_message?: ChatMessage[];
  subscription_person?: SubscriptionPerson[];
  person_contact?: PersonContact[];
  chat_person?: ChatPerson[];
  person_user?: PersonUser[];
  person_address?: PersonAddress[];
  payment?: Payment[];
  person_value?: PersonValue[];
  subscription_cancel?: SubscriptionCancel[];
  rating?: Rating[];
  wallet_person?: WalletPerson[];
}