export declare const EMOJIS: {
    HEART: string | undefined;
    COFFEE: string | undefined;
    BEER: string | undefined;
    BROKEN_HEART: string | undefined;
    CRYING: string | undefined;
    HEART_EYES: string | undefined;
    JOY: string | undefined;
    KISSING: string | undefined;
    SCREAM: string | undefined;
    ROCKET: string | undefined;
    SMIRK: string | undefined;
    RAISED_HANDS: string | undefined;
    POINT_RIGHT: string | undefined;
    ZAP: string | undefined;
    BOOM: string | undefined;
    PRAY: string | undefined;
    WINE: string | undefined;
    HEDGEHOG: string | undefined;
    CONFIG: string | undefined;
    WARNING: string | undefined;
    FIRE: string | undefined;
    OK: string | undefined;
    CHECK: string | undefined;
};
